-- Create invoices table for storing Stripe invoice records
-- This table stores all invoices generated by Stripe for customer payments

CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  stripe_invoice_id TEXT UNIQUE NOT NULL,
  stripe_customer_id TEXT NOT NULL,
  invoice_number TEXT,
  amount_due BIGINT NOT NULL, -- Amount in cents
  amount_paid BIGINT NOT NULL DEFAULT 0, -- Amount in cents
  currency TEXT NOT NULL DEFAULT 'usd',
  status TEXT NOT NULL, -- draft, open, paid, void, uncollectible
  invoice_pdf TEXT, -- URL to PDF
  hosted_invoice_url TEXT, -- URL to Stripe hosted invoice page
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  due_date TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_invoices_user_id ON invoices(user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_stripe_invoice_id ON invoices(stripe_invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_created_at ON invoices(created_at DESC);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_invoices_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_invoices_updated_at
  BEFORE UPDATE ON invoices
  FOR EACH ROW
  EXECUTE FUNCTION update_invoices_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Users can view their own invoices
CREATE POLICY "Users can view own invoices"
  ON invoices
  FOR SELECT
  USING (auth.uid() = user_id);

-- Service role can insert/update invoices (for webhook)
CREATE POLICY "Service role can insert invoices"
  ON invoices
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update invoices"
  ON invoices
  FOR UPDATE
  USING (true);

-- Grant permissions
GRANT SELECT ON invoices TO authenticated;
GRANT ALL ON invoices TO service_role;

-- Add comment
COMMENT ON TABLE invoices IS 'Stores Stripe invoice records for VAT filing and record-keeping';
